name:pull-request CI/CD yml

on :
env:
  BASE_IMAGE: ghcr.io/graphprotocol/graph-docs-staging

jobs:
  test : from test select most compatable requirement
  
    if: contains(github.head_ref, 'crowdin') == false
    runs-on: ubuntu-latest
    steps:
      - name: pass Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Lint and typecheck
        run: pnpm check

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # required to respect .dockerignore
          cache-from: type=registry,ref=${{ env.BASE_IMAGE }}:latest
          push: true
